CREATE OR REPLACE TABLE _SNOW_DB_.SNOW_GIT_INT_SCH.GIT_REPO_MASTER
(
    ENVIRONMENT VARCHAR,                 -- DEV / TEST / PROD
    DATABASE_NAME VARCHAR,               -- DB1_DEV, DB1_TEST, DB1_PROD
    SCHEMA_NAME VARCHAR, 
    GIT_REPO_NAME VARCHAR,             -- Snowflake GIT REPO object name
    ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR, 
    UPDATED_TS TIMESTAMP_NTZ
);

--insert into _SNOW_DB_.SNOW_GIT_INT_SCH.GIT_REPO_MASTER 
(ENVIRONMENT,DATABASE_NAME,SCHEMA_NAME,GIT_REPO_NAME,ACTIVE_FLAG,CREATED_TS,CREATED_BY,UPDATED_TS)
VALUES
('PROD','_SNOW_DB_','SNOW_GIT_INT_SCH','SNOW_GIT_INT_REPO',TRUE,CURRENT_TIMESTAMP(),CURRENT_USER(),CURRENT_TIMESTAMP());