CREATE OR ALTER TABLE SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH.DEPLOYMENT_PARAMETER_VALUES (
    PARAMETER_NAME VARCHAR, 
    PARAMETER_VALUE VARCHAR,
    CREATED_TIMESTAMP TIMESTAMP,
    CREATED_BY VARCHAR
);