CREATE OR ALTER TABLE SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH.NATION_STG(
NATION_ID NUMBER,
NATION_NAME VARCHAR,
REGION_ID NUMBER,
INSERT_TIMESTAMP TIMESTAMP,
UPDATE_TIMESTAMP TIMESTAMP
);

MERGE INTO SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH.NATION_STG as tgt
USING SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH.NATION_EX as src
ON tgt.NATION_ID = src.N_NATIONKEY
WHEN MATCHED THEN 
    UPDATE SET 
    NATION_ID = src.N_NATIONKEY,
    NATION_NAME = src.N_NAME,
    REGION_ID = src.N_REGIONKEY,
    UPDATE_TIMESTAMP = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (NATION_ID,NATION_NAME,REGION_ID, INSERT_TIMESTAMP)
    VALUES(src.N_NATIONKEY,src.N_NAME,src.N_REGIONKEY,current_timestamp());

    
N_NATIONKEY,
N_NAME,
N_REGIONKEY,
N_COMMENT