SHOW COLUMNS IN VIEW SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH.CUSTOMER_EX;

CREATE OR ALTER TABLE SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH.CUSTOMER_STG(
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR,
CUSTOMER_ADDRESS VARCHAR,
CUSTOMER_NATION VARCHAR,
PHONE_NUMBER VARCHAR,
ACCOUNT_BALANCE NUMBER,
MARKET_SEGMENT VARCHAR, 
INSERT_TIMESTAMP TIMESTAMP, 
UPDATE_TIMESTAMP TIMESTAMP
);


MERGE INTO SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH.CUSTOMER_STG as tgt
USING SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH. CUSTOMER_EX as src
ON tgt.CUSTOMER_ID = src.C_CUSTKEY
WHEN MATCHED THEN 
    UPDATE SET 
    CUSTOMER_ID  = src.C_CUSTKEY,
    CUSTOMER_NAME  = src.C_NAME,
    CUSTOMER_ADDRESS = src.C_ADDRESS,
    CUSTOMER_NATION = src.C_NATIONKEY,
    PHONE_NUMBER = src.C_PHONE,
    ACCOUNT_BALANCE  = src.C_ACCTBAL,
    MARKET_SEGMENT  = C_MKTSEGMENT,
    UPDATE_TIMESTAMP = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_ADDRESS,
    CUSTOMER_NATION, 
    PHONE_NUMBER,
    ACCOUNT_BALANCE, 
    MARKET_SEGMENT, 
    INSERT_TIMESTAMP
    )
    VALUES(
    src.C_CUSTKEY,
    src.C_NAME,
    src.C_ADDRESS,
    src.C_NATIONKEY,
    src.C_PHONE,
    src.C_ACCTBAL,
    src.C_MKTSEGMENT,
    current_timestamp());

    
