-- BASE CONFIG - DB+SCHEMA+WAREHOUSE+ROLE
CREATE DATABASE SNOW_GIT_INT_DB;
CREATE SCHEMA SNOW_GIT_INT_SCH;

CREATE ROLE SNOW_GIT_INT_DEV_RL;

GRANT ALL PRIVILEGES ON DATABASE SNOW_GIT_INT_DB TO ROLE SNOW_GIT_INT_DEV_RL;
GRANT ALL PRIVILEGES ON SCHEMA SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH TO ROLE SNOW_GIT_INT_DEV_RL;

GRANT ROLE SNOW_GIT_INT_DEV_RL TO ROLE ACCOUNTADMIN;

CREATE WAREHOUSE SNOW_GIT_INT_WH
WITH WAREHOUSE_SIZE = 'X-SMALL'
WAREHOUSE_TYPE = 'STANDARD'
SCALING_POLICY = 'STANDARD'
AUTO_RESUME = TRUE
AUTO_SUSPEND = 60
MAX_CLUSTER_COUNT = 2;

GRANT USAGE ON WAREHOUSE SNOW_GIT_INT_WH TO ROLE SNOW_GIT_INT_DEV_RL;
