CREATE OR REPLACE SECRET _SNOW_DB_.SNOW_GIT_INT_SCH.SNOW_GIT_INT_SEC
  TYPE = password
  USERNAME = '<git_user_name>'
  PASSWORD = 'ghp_token';

CREATE OR REPLACE API INTEGRATION SNOW_GIT_INT
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/pythonwithanish/SNOW_GIT_INTEGRATION')
  ALLOWED_AUTHENTICATION_SECRETS = (_SNOW_DB_.SNOW_GIT_INT_SCH.SNOW_GIT_INT_SEC)
  ENABLED = TRUE;


CREATE GIT REPOSITORY _SNOW_DB_.SNOW_GIT_INT_SCH.SNOW_GIT_INT_REPO 
API_INTEGRATION = SNOW_GIT_INT 
ORIGIN = 'https://github.com/pythonwithanish/SNOW_GIT_INTEGRATION';