CREATE OR REPLACE TABLE SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH.DEPLOY_PARAM_VALUES (
    ENVIRONMENT VARCHAR,
    PARAMETER_NAME VARCHAR, 
    PARAMETER_VALUE VARCHAR,
    CREATED_TIMESTAMP TIMESTAMP,
    CREATED_BY VARCHAR
);


--alter table SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH.DEPLOYMENT_PARAMETER_VALUES RENAME TO SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH.DEPLOY_PARAM_VALUES;