CREATE OR REPLACE TABLE SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH.DEPLOY_PARAM_VALUES (
    ENVIRONMENT VARCHAR,
    PARAMETER_NAME VARCHAR, 
    PARAMETER_VALUE VARCHAR,
    CREATED_TIMESTAMP TIMESTAMP,
    CREATED_BY VARCHAR
);

--INSERT INTO SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH.DEPLOY_PARAM_VALUES
(ENVIRONMENT,PARAMETER_NAME, PARAMETER_VALUE, CREATED_TIMESTAMP, CREATED_BY)
VALUES
('PROD','_SNOW_INT_RL','SNOW_GIT_INT_DEV_RL',CURRENT_TIMESTAMP(),CURRENT_USER()),
('PROD','_SNOW_DB_','SNOW_GIT_INT_DB',CURRENT_TIMESTAMP(),CURRENT_USER());

--alter table SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH.DEPLOYMENT_PARAMETER_VALUES RENAME TO SNOW_GIT_INT_DB.SNOW_GIT_INT_SCH.DEPLOY_PARAM_VALUES;
